LAB1-FINAL/Controllers/S_PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Diagnostics;
using LAB1_FINAL.Models;
using LAB1_FINAL.Helpers;

namespace LAB1_FINAL.Controllers
{
    public class S_PlayerController : Controller
    {
        // GET: S_Player
        Stopwatch ST = new Stopwatch();

        public ActionResult Index()
        {
            ST.Restart();
            var player1 = new PlayerModel { Name = "José", LastName = "De Leon", Position = "MD", Club = "CHI", Salary = 30000, };
            PlayerModel.S_Save(player1);
            PlayerModel.Log(Convert.ToString(ST.ElapsedTicks), "Consulta de Lista C#.");
            return View(Storage.Instance.S_playerList);
        }

        public ActionResult MostrarLog()
        {
            return View();
        }

        // GET: S_Player/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: S_Player/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: S_Player/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            ST.Restart();
            string s = "";
            // TODO: Add insert logic here
            try
            {
                var player = new PlayerModel
                {
                    Name = collection["Name"],
                    LastName = collection["LastName"],
                    Club = collection["Club"],
                    Position = collection["Position"],
                    Salary = int.Parse(collection["Salary"]),
                };

                PlayerModel.S_Save(player);
                PlayerModel.Log(Convert.ToString(ST.ElapsedTicks), "Creación de jugador manual en Lista C#.");
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: S_Player/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        public ActionResult S_CSV()
        {
            return View();
        }

        // POST: S_Player/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: S_Player/Delete/5
        public ActionResult Delete(string id)
        {
            ST.Restart();
            try
            {
                var player = new PlayerModel();
                foreach (var item in Storage.Instance.S_playerList)
                {
                    if (item.Name == id)
                    {
                        player = item;
                    }
                }
                Storage.Instance.S_playerList.Remove(player);
                PlayerModel.Log(Convert.ToString(ST.ElapsedTicks), "Eliminación de jugador en Lista C#.");
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }

        // POST: S_Player/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            return View();
        }

        //Search on LinkedList of C# players with espcific name 
       public ActionResult SearchByName()
        {
            return View();
        }
        public ActionResult Index_player(FormCollection collection)
        {
            ST.Restart();
            try
            {
                string idName = collection["Name"];
                PlayerModel player = new PlayerModel();

                foreach (var item in Storage.Instance.S_playerList)
                {
                    if (item.Name == idName || item.LastName == idName)
                    {
                        player = item;
                    }
                }
                PlayerModel.Log(Convert.ToString(ST.ElapsedTicks), "Búsqueda de jugador en Lista C#.");
                return View(player);
            }
            catch 
            {
                return View();
            }
        }

        //Search on LinkedList of C# players with the same position 
        public ActionResult Index_positions()
        {
            return View(Storage.Instance.S_CurrentplayerList);
        }
        // GET: S_Player/SearchByPosition/5
        public ActionResult SearchByPosition()
        {
            return View();
        }
        // POST: S_Player/SearchByPosition
        [HttpPost]
        public ActionResult SearchByPosition(FormCollection collection)
        {
            ST.Restart();
            // TODO: Add insert logic here
            try
            {
                string idPosition = collection["Position"];
                Storage.Instance.S_CurrentplayerList.Clear();
                foreach (var item in Storage.Instance.S_playerList)
                {
                    if (item.Position == idPosition)
                    {
                        var current = new PlayerModel();
                        current = item;
                        Storage.Instance.S_CurrentplayerList.AddLast(current);
                    }
                }
                PlayerModel.Log(Convert.ToString(ST.ElapsedTicks), "Búsqueda de jugador por posición en Lista C#.");
                return RedirectToAction("Index_positions");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult CSV(HttpPostedFileBase postedfile)
        {
            ST.Restart();
            string FilePath;
            if (postedfile != null)
            {
                string Path = Server.MapPath("~/Subidas/");
                if (!Directory.Exists(Path))
                {
                    Directory.CreateDirectory(Path);
                }
                FilePath = Path + System.IO.Path.GetFileName(postedfile.FileName);
                postedfile.SaveAs(FilePath);
                string csvData = System.IO.File.ReadAllText(FilePath);
                foreach (string row in csvData.Split('\n'))
                {
                    if (!string.IsNullOrEmpty(row))
                    {
                        try
                        {

                            var player = new PlayerModel
                            {
                                Name = row.Split(',')[2],
                                LastName = row.Split(',')[1],
                                Club = row.Split(',')[0],
                                Position = row.Split(',')[3],
                                Salary = Convert.ToInt32(Convert.ToDouble(row.Split(',')[4])),

                            };
                            PlayerModel.S_Save(player);
                        }
                        catch
                        {
                        }
                    }
                }
            }
            PlayerModel.Log(Convert.ToString(ST.ElapsedTicks), "Importación de jugadores en Lista C# mediante CSV.");
            return RedirectToAction("Index");
        }

    }
}

LAB1-FINAL/Views/S_Player/Create.cshtml
@model LAB1_FINAL.Models.PlayerModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PlayerModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAB1-FINAL/Views/S_Player/Index.cshtml
@model IEnumerable<LAB1_FINAL.Models.PlayerModel>

@{
    ViewBag.Title = "S_Index";
}

<h2>Standar List</h2>

<p>
<<<<<<< HEAD
    @Html.ActionLink("Create new", "Create") |
    @Html.ActionLink("Search name", "SearchByName") |
    @Html.ActionLink("Search positions", "SearchByPosition") |
    @Html.ActionLink("Search club", "SearchByClub") |
=======
    @Html.ActionLink("Create new", "Create")
    |  @Html.ActionLink("Search name", "SearchByName")
    |  @Html.ActionLink("Search positions", "SearchByPosition")
    |  @Html.ActionLink("Upload CSV", "S_CSV")
>>>>>>> 9d74e68f2ed4cd4982267d297ecac181bf56b333
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new {  id=item.Name })
        </td>
    </tr>
}

</table>

LAB1-FINAL/Views/S_Player/Index_club.cshtml
@model IEnumerable<LAB1_FINAL.Models.PlayerModel>

@{
    ViewBag.Title = "Index_club";
}

<h2>Club</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

LAB1-FINAL/Views/S_Player/Index_player.cshtml
@model LAB1_FINAL.Models.PlayerModel

@{
    ViewBag.Title = "Index_player";
}

<h2>Index_player</h2>

<div>
    <h4>PlayerModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

LAB1-FINAL/Views/S_Player/Index_positions.cshtml
@model IEnumerable<LAB1_FINAL.Models.PlayerModel>

@{
    ViewBag.Title = "Index_positions";
}

<h2>List of players with the same position</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

LAB1-FINAL/Views/S_Player/MostrarLog.cshtml
@using LAB1_FINAL.Models
@model IEnumerable<PlayerModel>

@{
    ViewBag.Title = "Log";
}

<h2>Log</h2>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CSV</title>
</head>
<body>
    <div class="form-horizontal">
        @Html.DisplayText(PlayerModel.LogMostrar);

    </div>
</body>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

</html>

LAB1-FINAL/Views/S_Player/S_CSV.cshtml
@using LAB1_FINAL.Models
@model IEnumerable<PlayerModel>

@{
    ViewBag.Title = "S_CSV";
}

<h2>CSV upload for Standard List</h2>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CSV</title>
</head>
<body>
    <div class="form-horizontal">
        @using (Html.BeginForm("CSV", "S_Player", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="postedFile" />
            <input type="submit" name="Import" />
        }
        
        </div>
</body>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

</html>

LAB1-FINAL/Views/S_Player/SearchByClub.cshtml
@model LAB1_FINAL.Models.PlayerModel

@{
    ViewBag.Title = "SearchByClub";
}

<h2>SearchByClub</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PlayerModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })           

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAB1-FINAL/Views/S_Player/SearchByName.cshtml
@model LAB1_FINAL.Models.PlayerModel

@{
    ViewBag.Title = "SearchByName";
}

<h2>Search by Name</h2>


@using (Html.BeginForm("Index_player","S_Player")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Standar List</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name,"Name / Last name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAB1-FINAL/Views/S_Player/SearchByPosition.cshtml
@model LAB1_FINAL.Models.PlayerModel

@{
    ViewBag.Title = "SearchByPosition";
}

<h2>SearchByPosition</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PlayerModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })       

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="BUSCAR" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}